hzCmd

diff --git a/bin/aws-create b/bin/aws-create
--- a/bin/aws-create
+++ b/bin/aws-create
@@ -1,15 +1,34 @@
 #!/usr/bin/env bash
 
-count=${1:-0}
-instanceType=${2:-c4.xlarge}
-outputFile=${3:-a.box}
+count="1"
+instanceType="c4.xlarge"
+outputFile="a.box"
+imageId="ami-08111162"
+region="us-east-1"
+key="jenkins-ec2-key"
+subnetId="subnet-378d2140"
+placement="hzpc2"
 
-imageId=${4:-ami-08111162}
-region=${5:-us-east-1}
+OPTS=`getopt -o : --long  count:,instanceType:,outputFile:,imageId:,region:,key:,subnetId:,placement: -n 'parse-options' -- "$@"` || { echo "Failed parsing options." >&2 ; exit 1; }
 
-key=${6:-jenkins-ec2-key}
-subnetId=${7:-subnet-378d2140}
-placement=${8:-hzpc2}
+initCmdArgs () {
+ eval set -- "$OPTS"
+
+ while true; do
+  case "$1" in
+    --count ) count="$2"; shift 2 ;;
+    --instanceType ) instanceType="$2"; shift 2 ;;
+    --outputFile ) outputFile="$2"; shift 2 ;;
+    --imageId ) imageId="$2"; shift 2 ;;
+    --region ) region="$2"; shift 2 ;;
+    --key ) key="$2"; shift 2  ;;
+    --subnetId ) subnetId="$2"; shift 2  ;;
+    --placement ) placement="$2"; shift 2  ;;
+    -- ) shift; break ;;
+    * ) break ;;
+  esac
+ done
+}
 
 
 if [ -f "${outputFile}" ]; then
