hzCmd

diff --git a/bin/aws-terminate b/bin/aws-terminate
--- a/bin/aws-terminate
+++ b/bin/aws-terminate
@@ -14,6 +14,10 @@ for boxFile in "${boxFiles}"; do
 
   id=$(echo ${line} | awk -F',' '{print $3}' )
   aws ec2 terminate-instances --instance-ids ${id}
+  rc=$?
+  if ((${rc} != 0)) ; then
+    echo "ERROR TERMINATING EC2 INSTANCE ${id}"
+  fi
 
  done
 
